# Docker-composer version
# ===============
version: "3.9"


# Docker Networks
# ===============
networks:
  myapp-network:
    driver: bridge


# Services
# ===============
services:

  # -------------------------------------------------
  # NGINX service
  # Access:
  # - http://localhost:8080/
  # -------------------------------------------------
  nginx:
    build:
      context: docker
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/myapp
    depends_on:
      - php-fpm
    networks:
      - myapp-network


  # -------------------------------------------------
  # PHP-FPM service
  # -------------------------------------------------
  php-fpm:
    build:
      context: docker
      dockerfile: php-fpm/Dockerfile
    container_name: php-fpm
    volumes:
      - ./:/myapp
    links:
      - mysql
      #- redis
    environment:
      APP_URL: http://localhost:8080
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=LOCAL_DOCKER
      DB_PORT: 3306
      DB_HOST: mysql
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
      REDIS_PORT: 6379
      REDIS_HOST: redis
      CACHE_DRIVER: redis
    networks:
      - myapp-network


  # -------------------------------------------------
  # PHP-CLI service
  # -------------------------------------------------
  php-cli:
    build:
      context: docker
      dockerfile: php-cli/Dockerfile
    container_name: php-cli
    tty: true
    volumes:
      - ./:/myapp
    links:
      - mysql
      #- redis
    environment:
      APP_URL: http://localhost:8080
      DB_PORT: 3306
      DB_HOST: mysql
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD:  ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
      REDIS_PORT: 6379
      REDIS_HOST: redis
      CACHE_DRIVER: redis
    networks:
      - myapp-network


  # -------------------------------------------------
  # MySQL service
  # -------------------------------------------------
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: always
    command: --lower_case_table_names=2
    ports:
      - "33061:3306"
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - myapp-network


  # -------------------------------------------------
  # REDIS service
  # -------------------------------------------------
  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - "63791:6379"
    networks:
      - myapp-network


  # -------------------------------------------------
  # NPM & NODE service
  # -------------------------------------------------
  node:
    build:
      context: docker
      dockerfile: node/Dockerfile
    container_name: node
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/cywapp
    tty: true
    networks:
      - myapp-network

